version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=your-ec2-public-ip
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
